// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzXAR8-52s3MI7oU4MN-n1TdlCalkSoFI',
    appId: '1:585133318036:web:b4c85e3ea7e4c0ef177981',
    messagingSenderId: '585133318036',
    projectId: 'flutter-mini-projet-8a8a2',
    authDomain: 'flutter-mini-projet-8a8a2.firebaseapp.com',
    storageBucket: 'flutter-mini-projet-8a8a2.firebasestorage.app',
    measurementId: 'G-2L8EP73HDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu81CCHOmxIUl4OeIKqUaa_sAV0MQIKDI',
    appId: '1:585133318036:android:81d943ee7d2dc8a3177981',
    messagingSenderId: '585133318036',
    projectId: 'flutter-mini-projet-8a8a2',
    storageBucket: 'flutter-mini-projet-8a8a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_8YKqx0m3HX1wGBnVyanqm3emakMEMwk',
    appId: '1:585133318036:ios:a15f0a2aab73177c177981',
    messagingSenderId: '585133318036',
    projectId: 'flutter-mini-projet-8a8a2',
    storageBucket: 'flutter-mini-projet-8a8a2.firebasestorage.app',
    iosBundleId: 'com.example.tp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv654Wa-38KgQxxdNeFLf-w95vQrGx_98',
    appId: '1:176857795462:ios:c82550046d4adbb3ce3a07',
    messagingSenderId: '176857795462',
    projectId: 'flutter-486f2',
    storageBucket: 'flutter-486f2.firebasestorage.app',
    iosBundleId: 'com.example.tp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzZCstE5ovQzlzuFFePg2-mLZquea1SRk',
    appId: '1:176857795462:web:2af5e9dcd423d0c3ce3a07',
    messagingSenderId: '176857795462',
    projectId: 'flutter-486f2',
    authDomain: 'flutter-486f2.firebaseapp.com',
    storageBucket: 'flutter-486f2.firebasestorage.app',
    measurementId: 'G-LPPRK70G4F',
  );

}